name: Get All Changed/Modified Files

on: [push, pull_request]

jobs:
  get_modified_files:
    name: Get modified files 
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: check differences
        run: |
          echo ${{steps.files.outputs.modified}}
  
  get_all_changed_files:
    name: Get all changed files
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: check added files
        run: |
          echo ${{steps.files.outputs.added}}